#!/usr/bin/env python
#
# $Id: pIIASCII,v 0.1 2005/11/05 03:41:59 nicb Exp $
#
import PII.RendererASCII
import sys

r = PII.RendererASCII.RendererASCII()

argc = len(sys.argv)

if argc > 1:
	n = 1
	while n < argc:
		mod = sys.argv[n]
		r.render_single(mod)
		n = n+1
else:
	r.render_all()
