#!/usr/bin/env python
#
# $Id: pIICsound,v 0.1 2005/11/11 06:09:09 nicb Exp $
#
import PII.RendererCsound
import sys

r = PII.RendererCsound.RendererCsound()

argc = len(sys.argv)

if argc > 1:
	n = 1
	while n < argc:
		mod = sys.argv[n]
		r.render_single(mod)
		n = n+1
else:
	r.render_all()
