#!/bin/sh
#
# $Id$
#
PIC='groff -p -mpic -P-l'
PYRENDERER='./PII/pIIPic.py'
VISUAL='gv -orientation=landscape -'
PDF='ps2pdf - pII.pdf'
OUTPUT=$VISUAL

usage()
{
	echo "Usage: $0 [-p|--pdf] [[mod1] ...]" 1>&2
	exit -1
}

COMMANDSTRING=$(getopt -o "p" --long "pdf" -- "$@")
eval set -- "$COMMANDSTRING"

while true
do
	case "$1" in
		-p|--pdf) OUTPUT=$PDF; shift;;
		--) shift; break;;
		*) usage;;
	esac
done

$PYRENDERER $@ | $PIC | $OUTPUT

exit 0
