#!/bin/sh
#
# $Id: plot-reverb 605 2006-07-04 16:39:41Z nicb $
#
# Calling sequence:
#
# ./plot-rms
#
LOGFILE="pII-FINAL.log"
SUFFIX="plot.tmpfile"
OUTFILE="pII-FINAL.riverbero.pdf"

out="riverbero.$SUFFIX"
grep "^riverbero" $LOGFILE | cut -d ' ' -f 2- \
	| awk '{ $2=(20/log(10))*log($2+1); $3=(20/log(10))*log($3+1);\
		printf("%8.4f %8.4f %8.4f\n",$1, $2, $3) }' > $out

(echo -e "set term postscript color";
cat <<EOF
	plot [][0:90] "$out" using 1:2 w lines lw 2 title "riverbero left",\
 				   "$out" using 1:3 w lines lw 2 title "riverbero right"
EOF
) | gnuplot | ps2pdf - > $OUTFILE

rm *.$SUFFIX

exit 0
